[server]
headless = true
enableCORS = false
enableXsrfProtection = false

[browser]
gatherUsageStats = false

[theme]
base = "light"
primaryColor = "#5046E4"
backgroundColor = "#F4F6FC"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#1E2433"
font = "sans serif"
